title: Knightish Writes

author:
  name: Knightish

description: >
  A site where I mostly talk about tabletop roleplaying games and video games.
  
remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    - { platform: bluesky, user_url: "https://bsky.app/profile/knightish.bsky.social" }
    - { platform: youtube, user_url: "https://www.youtube.com/@Knightishful" }
    - platform: kofi
      user_url: "https://ko-fi.com/knightish"
      title: Support me at my Ko-Fi!
